version: '2'
services:
  chess:
    container_name: chess
    build:
      context: ""
      dockerfile: Dockerfile
    image: chess
    ports:
      - "8080:8080"
    networks:
      - chess-network
    restart: always
    environment:
      SERVICE-NAME: chess
networks:
  chess-network:
    external: true